micronaut:
  application:
    name: crudOperation
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: ${DB_DRIVER:`org.postgresql.Driver`}
    username: ${DB_USER_NAME:`admin`}
    password: ${DB_PASSWORD:`admin@123`}
    schema-generate: CREATE
    dialect: postgres
netty:
  default:
    allocator:
      max-order: 3
